### PR TITLE
My PR

### PR DESCRIPTION
**Pull request by nicholasess**
- add compression in server
- add cors in server
- add Footer.css
- add babelrc and remove in webpack.config.js
- add gitignore

### CODE REVIEW

**Comment by jaburcodes** [comment]
Hey @nicholasess thanks for your contribution.

I have only one question, why did u change the identation of the whole project to 2?

**Comment by nicholasess** [comment]
@jaburcodes I use for default with prettier js in VS Code. As there is not file, the IDE setted files when i saved its
 You need create a lint file to define the project, then this is not will happen again.

**Comment by jaburcodes** [comment]
np, thats ok.

Lets follow the airBNB style guide, they talk about 2 spaces on identation.

Could you please solve the conflicts?

I would like to merge it.

Thanks

**Comment by nicholasess** [comment]
@jaburcodes resolved!

**Comment by jaburcodes** [comment]
I have a few questions:

Why did u remove the index.js file?
Why did u remove the "extract-text-webpack-plugin": "^2.1.2" from package.json?
And please, remove the npm debug file.

**Comment by nicholasess** [comment]
@jaburcodes I didn't remove index.js, can you see in commit, doesn't has file.
When I running git pull, returned 3.* in package, i just kept it

**Comment by jaburcodes** [comment]
If i merge your request the index.js file will be deleted and the extract-text-webpack-plugin": "^2.1.2" will ve removed from package.json.

please, fix it.

**Comment by nicholasess** [comment]
Where is the o file? Give me a link, please!

**Comment by nicholasess** [comment]
Forget, i will close PR and after i will send the contributions. 
Thanks

**Pull request closed without merging**
